#!/bin/bash
set -e
# Branded Calamares installer setup.
#
# Runs inside the live chroot (post_install_scripts) and only acts when
# Calamares is actually installed, so the generic builder stays unaware of it.
# Branding identity is read from /usr/lib/os-release; slideshow images and the
# logo are expected in the staging area created by the distribution's
# pre-chroot asset hook. Tune the variables below to taste.

# No /dev/null redirect here: the hook must also skip cleanly in a bare
# chroot where /dev is not yet mounted.
calamares_path=$(command -v calamares || true)
if [ -z "$calamares_path" ]; then
    echo 'Calamares not installed; skipping'
    exit 0
fi

# --- Identity -----------------------------------------------------------------
. /usr/lib/os-release
DISTRO_NAME="${NAME:-PersisOS}"
DISTRO_VERSION="${VERSION:-}"
BRAND_ID="${ID:-persisos}"
LOGO_NAME="${LOGO:-$BRAND_ID}"

# --- Layout -------------------------------------------------------------------
BRANDING_DIR="/usr/share/calamares/branding/$BRAND_ID"
CONF_DIR="/etc/calamares"
MODULES_DIR="$CONF_DIR/modules"
STAGED_ICONS="/.temp_assets/persisos-plasma-theme/usr/share/icons/hicolor/scalable/apps"
STAGED_WALLPAPERS="/.temp_assets/persisos-plasma-theme/usr/share/wallpapers"

DEFAULT_FILESYSTEM="ext4"

# --- Branding -----------------------------------------------------------------
install -d "$BRANDING_DIR/slides" "$MODULES_DIR"

LOGO="$STAGED_ICONS/$LOGO_NAME.svg"
if [ ! -f "$LOGO" ]; then
    echo "Warning: no logo at $LOGO; writing placeholder"
    LOGO="$BRANDING_DIR/logo.svg"
    printf '<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"/>' > "$LOGO"
fi
cp -f "$LOGO" "$BRANDING_DIR/logo.svg"

cat > "$BRANDING_DIR/branding.desc" <<EOF
---
componentName: $BRAND_ID
strings:
    productName:         "$DISTRO_NAME $DISTRO_VERSION"
    shortProductName:    "$DISTRO_NAME"
    version:             "$DISTRO_VERSION"
    shortVersion:        "$DISTRO_VERSION"
    versionedName:       "$DISTRO_NAME $DISTRO_VERSION"
    shortVersionedName:  "$DISTRO_NAME $DISTRO_VERSION"
    bootloaderEntryName: "$DISTRO_NAME"
images:
    productLogo:         "logo.svg"
    productIcon:         "logo.svg"
    productWelcome:      "logo.svg"
slideshow:               "show.qml"
slideshowAPI:            2
style:
   sidebarBackground:    "#2a2e32"
   sidebarText:          "#ffffff"
   sidebarTextSelect:    "#4d915e"
EOF

# Slideshow: cycle the staged slideshow wallpapers, one slide per image.
show="$BRANDING_DIR/show.qml"
cat > "$show" <<'EOF'
import QtQuick 2.15
import QtQuick.Controls 2.15

Presentation
{
    id: presentation
    Timer {
        interval: 8000
        running: true
        repeat: true
        onTriggered: presentation.goToNextSlide()
    }
EOF

slide_index=0
for image in "$STAGED_WALLPAPERS"/PersisOS-Slideshow/contents/images/*.png; do
    [ -f "$image" ] || { echo "Warning: no slideshow images found; slideshow will be empty"; break; }
    slide_index=$((slide_index + 1))
    cp -f "$image" "$BRANDING_DIR/slides/slide$slide_index.png"
    cat >> "$show" <<EOF

    Slide {
        Image {
            anchors.fill: parent
            fillMode: Image.PreserveAspectCrop
            source: "slides/slide$slide_index.png"
        }
    }
EOF
done
printf '}\n' >> "$show"
echo "Installed Calamares branding: $BRANDING_DIR"

# --- Settings -----------------------------------------------------------------
cat > "$CONF_DIR/settings.conf" <<EOF
# Generated for $DISTRO_NAME by hooks/installer/calamares.sh
modules-search: [ local ]
sequence:
      - locale
      - keyboard
      - welcome
      - partition
      - users
      - summary
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - localecfg
      - luksbootkeyfile
      - luksopenswaphookcfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - grubcfg
      - bootloader
      - umount
branding: $BRAND_ID
prompt-install: true
dont-chroot: false
oozes: []
EOF

# --- Module configuration -----------------------------------------------------
cat > "$MODULES_DIR/welcome.conf" <<'EOF'
requirements:
    requiredStorage: 8
    requiredRam: 2
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
EOF

cat > "$MODULES_DIR/partition.conf" <<EOF
# Generated by hooks/installer/calamares.sh
initialPartitioningChoices:
    defaultFileSystemType: $DEFAULT_FILESYSTEM
    luksFileSystemType: luks2
    eraseMode:
        swap: swap
drawNestedPartitions: false
alwaysShowPartitionLabels: true
efiFileSystemType: fat32
EOF

cat > "$MODULES_DIR/users.conf" <<'EOF'
# Generated by hooks/installer/calamares.sh
defaultGroups:
    - name: users
      mustExist: true
    - name: sudo
      mustExist: true
    - name: audio
      mustExist: true
    - name: video
      mustExist: true
    - name: plugdev
      mustExist: true
    - name: netdev
      mustExist: true
autologinGroup: autologin
doAutologin: false
sudoersGroup: sudo
setRootPassword: false
userShell: /bin/bash
hostname:
    location: EtcFile
    writeHostsFile: true
    template: "persisos"
EOF

cat > "$MODULES_DIR/displaymanager.conf" <<'EOF'
displaymanagers:
  - sddm
basicSetup: false
EOF

cat > "$MODULES_DIR/unpackfs.conf" <<'EOF'
# Live medium layout produced by the builder (live-boot)
unpack:
    - source: "/run/live/medium/live/filesystem.squashfs"
      sourcefs: "squashfs"
      destination: ""
EOF

# --- Launcher -----------------------------------------------------------------
# The whole live squashfs is copied to the target by unpackfs, so no extra
# package list is required post-install.
desktop_file="/usr/share/applications/install-$BRAND_ID.desktop"
install -d /usr/share/applications
cat > "$desktop_file" <<EOF
[Desktop Entry]
Type=Application
Name=Install $DISTRO_NAME
GenericName=System Installer
Comment=Install $DISTRO_NAME on this computer
TryExec=calamares
Exec=pkexec calamares
Icon=$LOGO_NAME
Terminal=false
StartupNotify=true
Categories=Qt;System;
Keywords=install;installer;system;${DISTRO_NAME,,};
EOF

# Also drop a launcher on the desktop for new users.
install -d /etc/skel/Desktop
install -m 0755 "$desktop_file" /etc/skel/Desktop/"${desktop_file##*/}"

echo "Created installer desktop launcher"
